// -----------------------------------------------------------------------------
// Testbench: lcg_tb
// Author: MrAbhi19
// Description:
//   This testbench verifies the functionality of the Linear Congruential Generator (LCG).
//   It applies a clock, reset, and seed, then observes the pseudo-random sequence
//   generated by the module. Waveform dump is enabled for viewing in GTKWave/ModelSim.
// -----------------------------------------------------------------------------

`timescale 1ns/1ps

module lcg_tb;

  // Testbench signals
  reg clk;
  reg rst;
  reg [30:0] seed;     // 31-bit seed
  wire [30:0] out;     // 31-bit output

  // Instantiate the LCG module
  lcg uut (
    .clk(clk),
    .rst(rst),
    .seed(seed),
    .out(out)
  );

  // Clock generation: 10ns period (100 MHz)
  always #5 clk = ~clk;

  initial begin
    // Initialize signals
    clk  = 0;
    rst  = 0;
    seed = 31'd83657912;   // Example seed value

    // Apply reset
    $display("Applying reset...");
    rst = 1;
    #10;
    rst = 0;

    // Run for several cycles
    $display("Starting LCG sequence...");
    repeat (20) begin
      @(posedge clk);
      $display("Time=%0t | out=%0d", $time, out);
    end

    // Finish simulation
    $display("Simulation complete.");
    $finish;
  end

  // ---------------------------------------------------------------------------
  // Waveform dump setup
  // ---------------------------------------------------------------------------
  initial begin
    $dumpfile("lcg_tb.vcd");   // Name of the waveform dump file
    $dumpvars(0, lcg_tb);      // Dump all signals in this testbench
  end

endmodule
